import type { Locale } from '@/i18n/config';

const copy = {
  en: {
    refresh: 'Refresh',
    scanning: 'Scanning storage...',
    delete: 'Delete',
    deleteGroup: 'Delete group',
    confirm: 'Confirm',
    used: 'Used',
    quota: 'Quota',
    databaseEntries: 'Database entries',
    fileGroups: 'File model groups',
    databases: 'Databases',
    fileStorage: 'File storage',
    toolStorage: 'Tool storage',
    siteSettings: 'Site settings',
    unassignedModels: 'Unassigned models',
    data: 'Data',
    model: 'Model',
    entries: 'entries',
    files: 'files',
    item: 'Item',
    source: 'Source',
    size: 'Size',
    action: 'Action',
    noDatabaseEntries: 'No database entries found.',
    noFileGroups: 'No file storage groups found.',
    noToolStorage: 'No tool storage found.',
    unsupported: 'Not supported by this browser.',
    localStorage: 'localStorage',
    indexedDb: 'IndexedDB',
    cacheStorage: 'Cache Storage',
    opfs: 'Origin private file system',
    siteFiles: 'Site files',
    storageError: 'Storage scan failed.',
    unknownQuota: 'Unknown',
    unavailableSize: 'Size unavailable',
    samplePaths: 'Sample paths',
    valuePreview: 'Value preview',
  },
  ja: {
    refresh: '更新',
    scanning: 'ストレージを確認中...',
    delete: '削除',
    deleteGroup: 'グループを削除',
    confirm: '確認',
    used: '使用量',
    quota: '上限',
    databaseEntries: 'データベース項目',
    fileGroups: 'ファイルモデルグループ',
    databases: 'データベース',
    fileStorage: 'ファイルストレージ',
    toolStorage: 'ツール別ストレージ',
    siteSettings: 'サイト設定',
    unassignedModels: '未分類モデル',
    data: 'データ',
    model: 'モデル',
    entries: '項目',
    files: 'ファイル',
    item: '項目',
    source: 'ソース',
    size: 'サイズ',
    action: '操作',
    noDatabaseEntries: 'データベース項目はありません。',
    noFileGroups: 'ファイルストレージグループはありません。',
    noToolStorage: 'ツールのストレージはありません。',
    unsupported: 'このブラウザでは対応していません。',
    localStorage: 'localStorage',
    indexedDb: 'IndexedDB',
    cacheStorage: 'Cache Storage',
    opfs: 'Origin private file system',
    siteFiles: 'サイトファイル',
    storageError: 'ストレージの確認に失敗しました。',
    unknownQuota: '不明',
    unavailableSize: 'サイズ不明',
    samplePaths: 'パス例',
    valuePreview: '値のプレビュー',
  },
  'zh-CN': {
    refresh: '刷新',
    scanning: '正在扫描存储...',
    delete: '删除',
    deleteGroup: '删除整组',
    confirm: '确认删除',
    used: '已使用',
    quota: '配额',
    databaseEntries: '数据库条目',
    fileGroups: '文件模型组',
    databases: '数据库',
    fileStorage: '文件存储',
    toolStorage: '按工具分组',
    siteSettings: '站点设置',
    unassignedModels: '未归属模型',
    data: '数据',
    model: '模型',
    entries: '条',
    files: '个文件',
    item: '项目',
    source: '来源',
    size: '大小',
    action: '操作',
    noDatabaseEntries: '没有发现数据库条目。',
    noFileGroups: '没有发现文件存储模型组。',
    noToolStorage: '没有发现工具存储。',
    unsupported: '当前浏览器不支持。',
    localStorage: 'localStorage',
    indexedDb: 'IndexedDB',
    cacheStorage: 'Cache Storage',
    opfs: 'Origin 私有文件系统',
    siteFiles: '站点文件',
    storageError: '存储扫描失败。',
    unknownQuota: '未知',
    unavailableSize: '大小不可用',
    samplePaths: '路径样例',
    valuePreview: '值预览',
  },
} satisfies Record<Locale, Record<string, string>>;

type StorageManagerCopyKey = keyof (typeof copy)['en'];

export function storageText(locale: Locale, key: StorageManagerCopyKey): string {
  return copy[locale][key] ?? copy.en[key];
}
